// Mocks generated by Mockito 5.4.6 from annotations
// in medisupply_app/test/pages/orders_pages/orders_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i7;
import 'dart:ui' as _i11;

import 'package:http/http.dart' as _i2;
import 'package:medisupply_app/src/classes/order.dart' as _i9;
import 'package:medisupply_app/src/classes/products_group.dart' as _i8;
import 'package:medisupply_app/src/classes/user.dart' as _i3;
import 'package:medisupply_app/src/providers/login_provider.dart' as _i10;
import 'package:medisupply_app/src/services/fetch_data.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FetchData].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchData extends _i1.Mock implements _i4.FetchData {
  MockFetchData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  String get baseUrlMaps =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrlMaps),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#baseUrlMaps),
            ),
          )
          as String);

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i6.Future<_i3.User> login(String? sEmail, String? sPassword) =>
      (super.noSuchMethod(
            Invocation.method(#login, [sEmail, sPassword]),
            returnValue: _i6.Future<_i3.User>.value(
              _FakeUser_1(this, Invocation.method(#login, [sEmail, sPassword])),
            ),
          )
          as _i6.Future<_i3.User>);

  @override
  _i6.Future<bool> logout(String? sRefreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [sRefreshToken]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<Map<String, dynamic>> getCoordinates(String? sAddress) =>
      (super.noSuchMethod(
            Invocation.method(#getCoordinates, [sAddress]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<bool> createAccount({
    required String? sName,
    required String? sTaxId,
    required String? sEmail,
    required String? sAddress,
    required String? sPhone,
    required String? sInstitutionType,
    required _i7.File? logoFile,
    required String? sSpecialty,
    required String? sApplicatName,
    required String? sApplicatEmail,
    required double? dLatitude,
    required double? dLongitude,
    required String? sPassword,
    required String? sPasswordConfirmation,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAccount, [], {
              #sName: sName,
              #sTaxId: sTaxId,
              #sEmail: sEmail,
              #sAddress: sAddress,
              #sPhone: sPhone,
              #sInstitutionType: sInstitutionType,
              #logoFile: logoFile,
              #sSpecialty: sSpecialty,
              #sApplicatName: sApplicatName,
              #sApplicatEmail: sApplicatEmail,
              #dLatitude: dLatitude,
              #dLongitude: dLongitude,
              #sPassword: sPassword,
              #sPasswordConfirmation: sPasswordConfirmation,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<_i8.ProductsGroup>> getProductsbyProvider(
    String? sAccessToken,
    String? sUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsbyProvider, [sAccessToken, sUserId]),
            returnValue: _i6.Future<List<_i8.ProductsGroup>>.value(
              <_i8.ProductsGroup>[],
            ),
          )
          as _i6.Future<List<_i8.ProductsGroup>>);

  @override
  _i6.Future<List<_i9.Order>> getOrders(
    String? sAccessToken,
    String? sUserId,
    String? sRole,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrders, [sAccessToken, sUserId, sRole]),
            returnValue: _i6.Future<List<_i9.Order>>.value(<_i9.Order>[]),
          )
          as _i6.Future<List<_i9.Order>>);

  @override
  _i6.Future<bool> createOrder(
    String? sAccessToken,
    Map<String, dynamic>? mOrder,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [sAccessToken, mOrder]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [LoginProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginProvider extends _i1.Mock implements _i10.LoginProvider {
  MockLoginProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get bLoading =>
      (super.noSuchMethod(Invocation.getter(#bLoading), returnValue: false)
          as bool);

  @override
  set oUser(_i3.User? oUser) => super.noSuchMethod(
    Invocation.setter(#oUser, oUser),
    returnValueForMissingStub: null,
  );

  @override
  set bLoading(bool? bLoading) => super.noSuchMethod(
    Invocation.setter(#bLoading, bLoading),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
